services:
  redis:
    image: redis:latest
    restart: unless-stopped

  url-shortener:
    build:
      context: .
    container_name: url-shortener
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      EnableSwagger: true
      ConnectionStrings__Redis: redis:6379,abortConnect=False
      BaseUrl: http://localhost:8080/
    depends_on:
      - redis

  